package com.kittenmp.ai

@RequiresOptIn(
    level = RequiresOptIn.Level.WARNING,
    message =
        "This code was generated by AI and has not been thoroughly reviewed or rewritten by a human.",
)
@Retention(AnnotationRetention.BINARY)
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.CLASS)
annotation class ComprehensionDebt(
    val agent: String = "",
    val model: String = "",
)
